name: tangramx-env
dependencies:
  - python>=3.8.5
  - pip=20.2.2
  - pytorch=1.4.0
  - scipy=1.5.2
  - matplotlib-base=3.3.1
  - seaborn=0.11.1
  - jupyterlab=2.2.6
  - nb_conda=2.2.1
  - pip:
    - numpy>=1.22
    - numba==0.58.1
    - pandas==1.2.0
    - zipp==3.20
    - scanpy>=1.6.0
    - scikit-learn
    - tqdm
    - libpysal
    - squidpy